SET LINESIZE 200
SET PAGESIZE 100
COLUMN TABLE_NAME FORMAT A20
COLUMN CONSTRAINT_NAME FORMAT A30
COLUMN CONSTRAINT_TYPE FORMAT A15
COLUMN SEARCH_CONDITION FORMAT A40

PROMPT --- USER_TABLES ---
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;

PROMPT --- USER_CONSTRAINTS ---
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME IN ('CUSTOMER', 'VEHICLE', 'SERVICE_RECORD')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

EXIT;
